[package]
name = "geo-test-fixtures"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
geo-types = { version = "0.7.11", features = [
    "approx",
    "use-rstar_0_11",
], registry = "franklin-ai-geo" }
wkt = { version = "0.10.0", default-features = false }
